### ISSUE TITLE
No setup instructions

### ISSUE THREAD

**Issue by bhoeting** [lufinkey/basic-php-framework#1]
Hello

I overheard in some talk in a hacker-innovation-safe-space about a hip new PHP framework "basic-php-framework."  I really would like to use this for my StartUp but I can't figure out how to create a project with it.  Could you please include a readme with setup instructions?  Please and thanks you

Cheers

**Comment by lufinkey** [comment]
3e638d9abd8a66ffa226b3eac462d90ff3b08047 closes this issue
