### ISSUE TITLE
 I have quite a simple question about URL rewriting subcategory and category URL

### ISSUE THREAD

**Issue by parush23** [lufinkey/basic-php-framework#2]
Hello everybody!

I have quite a simple question about URL rewriting subcategory and category URL, I can't find any solution to this problem (due to lack of my deeper apache programming knowledge).
Here is my problem/question:

we have two website url that causes a duplicate problem in this URL Both of files in the company folder(showcategoryPage,showsubcategoryPage) Both of the folder not work same time. i have to comment on one code then its work.

domain.com/company/automobiledirectory                           (showcategoryPage)
domain.com/company/automobiledirectory/automotive-led-light      (showsubcategoryPage)

This is .Htaccss File code
Options +FollowSymlinks
RewriteEngine On

#RewriteBase /

#RewriteCond !{HTTPS} off
#RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
#RewriteCond %{HTTP_HOST} !^www\.
#RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

RewriteRule ^company/([a-zA-Z0-9_-]+)/([0-9]+)$  company/showcategory?cat_name=$1
RewriteRule ^company/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/$  company/showsubcategory?cat_name=$1&sub_cat_name=$2

# If the requested filename is not a directory,
RewriteCond %{REQUEST_FILENAME} !-d

# and if the requested filename is not a regular file that exists,
RewriteCond %{REQUEST_FILENAME} !-f

# and if the requested filename is not a symbolic link,
RewriteCond %{REQUEST_FILENAME} !-l

# then rewrite the URL in the following way:
# Take the whole request filename and provide it as the value of a
# "url" query parameter to index.php. Append any query string from
# the original URL as further query parameters (QSA), and stop
# processing this .htaccess file (L).

RewriteRule ^(.+)$ index.php?url=$1 [QSA,L]

Thanks for your help guys!

If You need any other details on our coding, just let me know.

**Comment by lufinkey** [comment]
To be honest, I haven't dealt with `.htaccess` files (or this project really) for a long time so I'm not really sure how to solve your problem :/ I'm sure I set up a few things wrong in this project's `.htaccess`
